### ISSUE TITLE
Refresh Token Issue

### ISSUE THREAD

**Issue by nmylarappa** [josuebrunel/yahoo-oauth#51]
I am having issues in getting the refresh token. Below is error

callback_uri oob
raw_access <Response [400]>
ac_tkn {u'error_description': u'Failed to decode/encode refresh token', u'error': u'INVALID_REFRESH_TOKEN'}

 self.access_token = parsed_access['access_token']
KeyError: 'access_toke

**Comment by nmylarappa** [comment]
Below is more details log details:

raw_access <Response [400]>
ac_tkn {u'error_description': u'Failed to decode/encode refresh token', u'error': u'INVALID_REFRESH_TOKEN'}
Traceback (most recent call last):
  File "/home/nmylarappa/dwh/Scripts/mktg_yahoo_campaign_d/pythonscripts/yahoo_to_json.py", line 112, in <module>
    main()
  File "/home/nmylarappa/dwh/Scripts/mktg_yahoo_campaign_d/pythonscripts/yahoo_to_json.py", line 25, in main
    oauth = OAuth2(None, None, from_file=secret_filename)
  File "/home/nmylarappa/dwh/Scripts/mktg_yahoo_campaign_d/pythonscripts/yahoo_oauth_2.py", line 238, in __init__
    super(OAuth2, self).__init__('oauth2', consumer_key, consumer_secret, **kwargs)
  File "/home/nmylarappa/dwh/Scripts/mktg_yahoo_campaign_d/pythonscripts/yahoo_oauth_2.py", line 89, in __init__
    data.update(self.refresh_access_token())
  File "/home/nmylarappa/dwh/Scripts/mktg_yahoo_campaign_d/pythonscripts/yahoo_oauth_2.py", line 206, in refresh_access_token
    credentials.update(self.oauth2_access_parser(raw_access))
  File "/home/nmylarappa/dwh/Scripts/mktg_yahoo_campaign_d/pythonscripts/yahoo_oauth_2.py", line 167, in oauth2_access_parser
    self.access_token = parsed_access['access_token']
KeyError: 'access_token'

**Comment by DMcP89** [comment]
Hi @nmylarappa  can you provide a bit more context? Maybe a link to your code or a large snippet?
